excerpt_separator   : "<!--more-->"
google_analytics_id : UA-45395039-3
highlighter         : pygments
markdown            : kramdown
permalink           : /news/:year/:month/:day/:title/
relative_permalinks : false
repository          : https://github.com/mgiaccone/restelio
timezone            : Europe/London



