markdown: kramdown
highlighter: pygments
timezone: Europe/London
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
google_analytics_id: UA-45395039-3

#excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
#repository: https://github.com/jekyll/jekyll
#help_url: https://github.com/jekyll/jekyll-help

