timezone: Europe/London
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false

#markdown: kramdown
#highlighter: pygments
#gauges_id: 503c5af6613f5d0f19000027
#excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
#repository: https://github.com/jekyll/jekyll
#help_url: https://github.com/jekyll/jekyll-help

#
google_analytics_id: UA-45395039-3
